version: "3.9"

services:

  task:
    build:
      context: task
    environment:
      - PGPASSWORD=postgres
      - PGUSER=postgres
    network_mode: host
  db:
    build:
      context: db
    ports:
      - 5432:6432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.db-data/:/var/lib/postgresql/data/

volumes:
  .db-data: