name: Build and push docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag and push image to Amazon ECR as `latest`
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: digital-land-postgres
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG task
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Build, tag and push image to Amazon ECR as `staging`
      if: ${{ github.ref == 'refs/heads/staging' }}
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: digital-land-postgres
        IMAGE_TAG: staging
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG task
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
